name: Tag Release

on: 
    pull_request:
        types:
            - opened
        branches:
            - main

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3     
        - name: Git tag
          run: |
            export version=$(git branch --show-current | sed 's:.*/::')
            echo $version
            git tag -a $version -m $version
            git push origin --tags